# You are given two strings:
# s
# t
# String t is generated by randomly shuffling s and adding one extra character.
# Return the extra character.
s = "abcd"
t = "abcde"

hash_s = {}

# Count frequency of characters in s
for ch in s:
    if ch in hash_s:
        hash_s[ch] += 1
    else:
        hash_s[ch] = 1

# Find the extra character in t
for ch in t:
    if ch not in hash_s:
        print("Extra character:", ch)
        break

    hash_s[ch] -= 1

    if hash_s[ch] < 0:
        print("Extra character:", ch)
        break
    
        
    
    
